name: CI with Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or '16', depending on your project

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test
